import 'dotenv/config';
import pg from 'pg';
const base = { host: process.env.DB_HOST, port: process.env.DB_PORT, user: process.env.DB_USER, password: process.env.DB_PASSWORD };
const snap = async (db) => {
  const c = new pg.Client({ ...base, database: db }); await c.connect();
  const cols = (await c.query(`SELECT table_name, column_name, data_type, is_nullable, column_default FROM information_schema.columns WHERE table_schema='public' ORDER BY 1,2`)).rows;
  const idx = (await c.query(`SELECT indexname, indexdef FROM pg_indexes WHERE schemaname='public'`)).rows;
  const cons = (await c.query(`SELECT conrelid::regclass::text t, conname, pg_get_constraintdef(oid) d FROM pg_constraint WHERE connamespace='public'::regnamespace`)).rows;
  const fns = (await c.query(`SELECT proname FROM pg_proc WHERE pronamespace='public'::regnamespace`)).rows.map(r => r.proname);
  await c.end();
  return { cols, idx, cons, fns };
};
const dev = await snap(process.env.DB_NAME), fresh = await snap('fullpetro_fresh_test');
const key = (r) => `${r.table_name}.${r.column_name}`;
const fc = new Map(fresh.cols.map(r => [key(r), r])), dc = new Map(dev.cols.map(r => [key(r), r]));
const ignore = (t) => /^(session|schema_migrations)$/.test(t);
const devTables = new Set(dev.cols.map(r => r.table_name)), freshTables = new Set(fresh.cols.map(r => r.table_name));
console.log('Tablas: desarrollo', devTables.size, '| nueva', freshTables.size);
console.log('Tablas que FALTAN en la nueva:', [...devTables].filter(t => !freshTables.has(t) && !ignore(t)).join(', ') || '(ninguna)');
console.log('Tablas que sobran en la nueva:', [...freshTables].filter(t => !devTables.has(t) && !ignore(t)).join(', ') || '(ninguna)');
const faltan = [...dc.keys()].filter(k => !fc.has(k) && !ignore(k.split('.')[0]) && freshTables.has(k.split('.')[0]));
console.log('Columnas que FALTAN en la nueva:', faltan.join(', ') || '(ninguna)');
const sobran = [...fc.keys()].filter(k => !dc.has(k) && devTables.has(k.split('.')[0]));
console.log('Columnas que sobran en la nueva:', sobran.join(', ') || '(ninguna)');
const difTipo = [...dc.keys()].filter(k => fc.has(k)).filter(k => { const a = dc.get(k), b = fc.get(k); return a.data_type !== b.data_type || a.is_nullable !== b.is_nullable; });
console.log('Columnas con tipo/nulo distinto:', difTipo.map(k => `${k} (dev ${dc.get(k).data_type}/${dc.get(k).is_nullable} vs nueva ${fc.get(k).data_type}/${fc.get(k).is_nullable})`).join('; ') || '(ninguna)');
const fi = new Set(fresh.idx.map(i => i.indexname));
console.log('Índices que FALTAN en la nueva:', dev.idx.filter(i => !fi.has(i.indexname) && !/session/.test(i.indexname)).map(i => i.indexname).join(', ') || '(ninguno)');
const fk = new Set(fresh.cons.map(c => `${c.t}|${c.d}`));
console.log('Restricciones que FALTAN en la nueva:', dev.cons.filter(c => !fk.has(`${c.t}|${c.d}`) && !/session/.test(c.t)).map(c => `${c.t}: ${c.conname}`).join('; ') || '(ninguna)');
const ff = new Set(fresh.fns);
console.log('Funciones que FALTAN en la nueva:', dev.fns.filter(f => !ff.has(f)).join(', ') || '(ninguna)');
