export * from "./login/login.jsx";
export * from "./forgot/forgot.jsx";
export * from "./reset/reset.jsx";
export * from "./dashboard/dashboard.jsx";
export * from "./notFound/notFound.jsx";
export { default as FuelReports } from "./reports/reportesCombustible.jsx";
export { default as HoursReports } from "./reports/reportesHoras.jsx";
export { default as Persons } from "./persons/persons.jsx";
export { default as Users } from "./users/users.jsx";
export { default as Profiles } from "./profiles/profiles.jsx";
export { default as FuelLightFleet } from "./fuel/fuelLightFleet.jsx";
export { default as FuelHeavyFleet } from "./fuel/fuelHeavyFleet.jsx";
export { default as FuelTank } from "./fuel/fuelTank.jsx";
export { default as Vehicles } from "./vehicles/vehicles.jsx";
export { default as Tracker } from "./tracker/tracker.jsx";
export { default as TrackerAlerts } from "./tracker/trackerAlerts.jsx";
export { default as TrackerMapPage } from "./tracker/trackerMap.jsx";
export { default as TrackerReport } from "./tracker/trackerReport.jsx";
export { default as HoursDailyEntry } from "./hours/dailyEntry.jsx";
export { default as HoursCompanies } from "./hours/companies.jsx";
export { default as HoursProjects } from "./hours/projects.jsx";
export { default as HoursEquipment } from "./hours/equipment.jsx";
export { default as FleetList } from "./fleet/fleetList.jsx";
export { default as FleetDetail } from "./fleet/fleetDetail.jsx";
export { default as FleetCatalog } from "./fleet/fleetCatalog.jsx";
export { default as FleetDrivers } from "./fleet/fleetDrivers.jsx";
